genome: "hg38"
hg38_bowtie2_index: "/auto/rcf-40/amalthom/panases_soft/Bowtie_Indexes/bowtie2_index/hg38.p10/hg38.p10"
hg38_bowtie1_index: "/home/rcf-40/amalthom/panases_soft/Bowtie_Indexes/bowtie/hg38.p10/hg38.p10"
hg38_blacklist: "/home/rcf-40/amalthom/panases_soft/genomes/blacklist/hg38.blacklist.bed"
hg38_sizes: "/home/rcf-40/amalthom/panases_soft/genomes/sizes/hg38.p10.sizes"
hg19_bowtie1_index: "/home/rcf-40/amalthom/panases_soft/Bowtie_Indexes/bowtie/hg19/hg19"
hg19_bowtie2_index: "/home/rcf-40/amalthom/panases_soft/Bowtie_Indexes/bowtie2_index/hg19/hg19"
hg19_blacklist: "/home/rcf-40/amalthom/panases_soft/genomes/blacklist/hg19_atac_consensusBlacklist.bed"
hg19_sizes: "/home/rcf-40/amalthom/panases_soft/genomes/sizes/human.hg19.sizes"
mm10_bowtie1_index: "/home/rcf-40/amalthom/panases_soft/Bowtie_Indexes/bowtie/mm10.p6/mm10.p6"
mm10_bowtie2_index: "/home/rcf-40/amalthom/panases_soft/Bowtie_Indexes/bowtie2_index/mm10.p6/mm10.p6"
mm10_blacklist: "/home/rcf-40/amalthom/panases_soft/genomes/blacklist/mm10.blacklist.bed"
mm10_sizes: "/home/rcf-40/amalthom/panases_soft/genomes/sizes/mouse.mm10.genome.sizes"
dm6_bowtie1_index: "/home/rcf-40/amalthom/panases_soft/Bowtie_Indexes/bowtie2_index/dm6/dm6"
picard_markdup: "/home/rcf-40/amalthom/panases_soft/picard_1.122/MarkDuplicates.jar"
tempdir: "/home/rcf-40/amalthom/staging_work"
